export const videoDataFromAPI = [];
export const videos = [
  {
    id: 1,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 2,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 3,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 4,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 5,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 6,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 7,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 8,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 9,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 10,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 12,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 13,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 11,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 22,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 23,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 24,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 25,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 26,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 27,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 28,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 29,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  },
  {
    id: 30,
    thumbnail: "/assets/thumbnails/1.jpg",
    title: "Danh sách nhạc kết hợp của tôi",
    channel: "Dangranto, Wxrdie, Andree Right Hand...",
    views: "1,2 Tr lượt xem",
    time: "Hôm nay",
    duration: "54:27",
    isPlaylist: true,
  },
  {
    id: 32,
    thumbnail: "/assets/thumbnails/2.jpg",
    title: "Khuôn Mặt Đáng Thương...",
    channel: "Sky Wave Remix",
    views: "336 N lượt xem",
    time: "1 tháng trước",
    duration: "54:27",
    isPlaylist: false,
  },
  {
    id: 33,
    thumbnail: "/assets/thumbnails/3.jpg",
    title: "BẮN CS OFFTRYM LÀ CHO CẢ MAP TẮM MÁU",
    channel: "Dev Nguyen",
    views: "16 N lượt xem",
    time: "3 giờ trước",
    duration: "43:08",
    isPlaylist: false,
  }
];